### ISSUE TITLE
Error: Unrecognized name: _dbt_max_partition 

### ISSUE THREAD

**Issue by babi4** [Velir/dbt-ga4#230]
I have error Unrecognized name: _dbt_max_partition  during incremental update

11:55:47  Database Error in model fct_ga4__pages (models/marts/core/fct_ga4__pages.sql)
11:55:47    Unrecognized name: _dbt_max_partition at [30:32]
11:55:47    compiled Code at target/run/ga4/models/marts/core/fct_ga4__pages.sql

dbt-core: 1.5.1,
bigquery: 1.5.1

  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: Velir/ga4
    version: 4.0.0

**Comment by adamribaudo-velir** [comment]
I can confirm this bug, but I'll also point out that we plan to deprecate the 'dynamic' max partition lookup in favor of the `static_incremental_days` variable. See discussion in #182 

Specifically, if we bring together 'daily' and 'intraday' data, we can no longer count on the `_dbt_max_partition` variable telling us where to pick up processing because we could have a partial amount of data for a day. The best approach is to use `static_incremental_days` and reprocess ~3 days of data on each incremental run.

**Comment by dgitis** [comment]
We've switched to requiring `static_incremental_days` in release 4.0 so there should be no more `_dbt_max_partition` errors.

**Comment by babi4** [comment]
14:00:46.494505 [debug] [MainThread]: 1602: parser fallback to jinja rendering on dbt_metrics_default_calendar.sql
14:00:46.508734 [debug] [MainThread]: 1699: static parser successfully parsed staging/stg_ga4__event_to_query_string_params.sql
14:00:46.510543 [debug] [MainThread]: 1699: static parser successfully parsed staging/stg_ga4__user_id_mapping.sql
14:00:46.512499 [debug] [MainThread]: 1699: static parser successfully parsed staging/stg_ga4__client_key_first_last_events.sql
14:00:46.514632 [debug] [MainThread]: 1603: static parser failed on staging/stg_ga4__session_conversions_daily.sql
14:00:46.520292 [error] [MainThread]: Encountered an error:
'NoneType' object cannot be interpreted as an integer
14:00:46.524126 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 215, in wrapper
    return func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 242, in wrapper
    manifest = ManifestLoader.get_full_manifest(
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 227, in get_full_manifest
    manifest = loader.load()
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 386, in load
    self.parse_project(
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 515, in parse_project
    parser.parse_file(block)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 433, in parse_file
    self.parse_node(file_block)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 394, in parse_node
    self.render_update(node, config)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/models.py", line 358, in render_update
    super().render_update(node, config)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 370, in render_update
    context = self.render_with_context(node, config)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 240, in render_with_context
    get_rendered(parsed_node.raw_code, context, parsed_node, capture_macros=True)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 591, in get_rendered
    return render_template(template, ctx, node)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 546, in render_template
    return template.render(ctx)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 2, in top-level template code
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 101, in safe_range
    rng = range(*args)
TypeError: 'NoneType' object cannot be interpreted as an integer

14:00:46.524795 [debug] [MainThread]: Command `dbt run` failed at 14:00:46.524718 after 2.11 seconds

11:00:44  Running with dbt=1.5.1
11:00:45  Unable to do partial parsing because saved manifest not found. Starting full parse.
11:00:46  Encountered an error:
'NoneType' object cannot be interpreted as an integer
11:00:46  Traceback (most recent call last):
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 142, in wrapper
    return func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 215, in wrapper
    return func(*args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/cli/requires.py", line 242, in wrapper
    manifest = ManifestLoader.get_full_manifest(
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 227, in get_full_manifest
    manifest = loader.load()
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 386, in load
    self.parse_project(
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/manifest.py", line 515, in parse_project
    parser.parse_file(block)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 433, in parse_file
    self.parse_node(file_block)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 394, in parse_node
    self.render_update(node, config)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/models.py", line 358, in render_update
    super().render_update(node, config)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 370, in render_update
    context = self.render_with_context(node, config)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/parser/base.py", line 240, in render_with_context
    get_rendered(parsed_node.raw_code, context, parsed_node, capture_macros=True)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 591, in get_rendered
    return render_template(template, ctx, node)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 546, in render_template
    return template.render(ctx)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 2, in top-level template code
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/babi4/Documents/work/SecretSanta_dbt/.venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 101, in safe_range
    rng = range(*args)
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by dgitis** [comment]
We could use a few more details, but if you are implementing `static_incremental_days` then the usual reason I get the NoneType object cannot be interpreted as an integer is because I'm using `static_incremental_days` in a model that I configured on my project or a package model that I've overridden in my project which doesn't have access to the GA4-scoped variable.

The solution is to set the variable in the project as well.
